version: '3.1'
services:
  nginx:
    restart: always
    image: nginx
    ports:
      - 81:81
      - 7777:7777
    volumes:
      - ./conf.d/:/etc/nginx/conf.d
      - /root/project/interview-blog/docs/.vuepress/dist:/usr/share/nginx/blog/